# The URL the site will be built for
base_url = "https://arasyidi.netlify.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hyde"
title = "Painfully Mediocre"
description = "rants & memes"

# list of series and tags
# series = [
#    "unemployment_arc", -> the story during my unemployment period (zenius lay-off)
#    "learn-in-public",
#    "python-speedup", -> how to make python faster
#    "core-value" -> what I deeply believe
# ]
# tags = [
#    "reading",
#    "python",
#    "data-science",
#    "career-retro",
#    "me-think",
#    "how-to",
    #    "beginner", -> basic use of a library/framework or the combination of it
    #    "intermediate", -> add some processing
    #    "advanced", -> low level?, processing with concepts that needed to be understood before, unfamiliar/uncommon data sources,
#    "geospatial"
# ]

taxonomies = [
    { name = "tags" },
    { name = "series" }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
hyde_links = [
    {url = "about/about", name = "About"},
    {url = "books/books", name = "Books"},
    {url = "series", name = "Series"},
    {url = "tags", name = "Tags"},
]
hyde_sticky = true
